[package]
name = "rustutil"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.3.0", features = ["derive"] }
git2 = "0.17.1"
serde = { version = "1.0.163", features = ["derive"] }
serde_json = "1.0.96"

[profile.release]
strip = true
lto = true